version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
          - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mySqldb
      - MYSQL_USER=dbUser
      - MYSQL_PASSWORD=ps34df
